language: android
jdk: oraclejdk8
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - sys-img-armeabi-v7a-android-23
    - sys-img-armeabi-v7a-android-25

script:
   - ./gradlew build connectedCheck